export const PROGRAMMING_LANGUAGES = {
	TypeScript: "/typescript.svg",
	JavaScript: "/javascript.svg",
	Python: "/python.svg",
	Java: "/java.svg",
	"C++": "/c++.svg",
	Swift: "/swift.svg",
	Csharp: "/csharp.svg",
	Go: "/go.svg",
	HTML: "/html.svg",
	CSS: "/css.svg",
    PHP:'/php.svg',
    Lua:'/lua.svg',
    Vue:'/vue.svg',
    EJS:'/ejs.svg',
    Handlebars:'/handlebars.svg',
    Hack:'/hack.svg',
	Dart:'/dart.svg',
	C:'/c.svg',
	Shell:'/shell.svg'
};